// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------ //
// ws2812 //
// ------ //

#define ws2812_wrap_target 0
#define ws2812_wrap 11

static const uint16_t ws2812_program_instructions[] = {
            //     .wrap_target
    0xe000, //  0: set    pins, 0                    
    0x6021, //  1: out    x, 1                       
    0x0028, //  2: jmp    !x, 8                      
    0xf501, //  3: set    pins, 1                [21]
    0xb542, //  4: nop                           [21]
    0xf200, //  5: set    pins, 0                [18]
    0xaf42, //  6: nop                           [15]
    0x0001, //  7: jmp    1                          
    0xf501, //  8: set    pins, 1                [21]
    0xf800, //  9: set    pins, 0                [24]
    0xb542, // 10: nop                           [21]
    0x0001, // 11: jmp    1                          
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program ws2812_program = {
    .instructions = ws2812_program_instructions,
    .length = 12,
    .origin = -1,
};

static inline pio_sm_config ws2812_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + ws2812_wrap_target, offset + ws2812_wrap);
    return c;
}
#endif

